# Generated by Django 5.2.7 on 2026-10-01 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='resume',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(200, 'Resumo deve ter no máximo 200 caracteres!')]),
        ),
    ]
